### ISSUE TITLE
Huggingface - Error importing library

### ISSUE THREAD

**Issue by FlorentLvr** [jupyter-naas/drivers#192]
![image](https://user-images.githubusercontent.com/48032461/140504060-825dae81-b276-4787-9d53-cf95d1c29a13.png)
![image](https://user-images.githubusercontent.com/48032461/140504180-ebee5073-7d84-4cb0-b485-512d41a76d7a.png)

**Comment by mertbozkir** [comment]
is anybody solve this problem?

**Comment by FlorentLvr** [comment]
Hi @mertbozkir,
Nobody has solved this issue for now.
@Dr0p42 has rework the __init__ in driver and Huggingface is not there.
Do you want to have a look at it ?
TY

**Comment by mertbozkir** [comment]
Ok, I will look after today (my last exam). I will reach you in Slack for the problem. 🧙‍♂️

**Comment by Dr0p42** [comment]
> Ok, I will look after today (my last exam). I will reach you in Slack for the problem. 🧙‍♂️

Good luck on you exam @mertbozkir 🤞.

I think this error is due to keras version and tensorflow version not matching.

**Comment by mertbozkir** [comment]
![image](https://user-images.githubusercontent.com/63906053/152697296-ded136b1-5f20-48b0-a5be-f267e8d342de.png)

**I guess the error is because of this tf.keras vs python/keras thing.** 

But I still didn't get the error. Tensorflow 2.6 and Keras 2.6 should be compatible 🧙🏼‍♂️

![image](https://user-images.githubusercontent.com/63906053/152697365-5e2e5a05-35f9-4b9e-83d8-f89fec9f6880.png)

**Comment by jravenel** [comment]
Also got this issue, I think it's the same problem 
<img width="964" alt="Screenshot 2022-03-20 at 18 46 26" src="https://user-images.githubusercontent.com/21052349/159178481-b7c67123-e0b7-4a50-8ed6-245781a21d67.png">

**Comment by jravenel** [comment]
>works now
